{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hubspotService.fullname" . }}-worker
  labels:
    {{- include "hubspotService.labels" . | nindent 4 }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "hubspotService.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{- include "hubspotService.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      containers:
        - name: worker
          image: {{ include "hubspotService.workerImage" . }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            {{- include "hubspotService.commonEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: kv-secrets
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: kv-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "hubspotService.fullname" . }}-spc
{{- end }}
