apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "hubspotService.fullname" . }}-spc
  labels:
    {{- include "hubspotService.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.keyVault.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.global.keyVault.name | quote }}
    tenantId: {{ .Values.global.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: hubspot-service-api-tokens
          objectType: secret
          objectAlias: hubspot-api-tokens
        - |
          objectName: hubspot-service-otp-webhook-token
          objectType: secret
          objectAlias: otp-webhook-token
        - |
          objectName: hubspot-service-redis-password
          objectType: secret
          objectAlias: redis-password
        - |
          objectName: users-service-jwt-secret
          objectType: secret
          objectAlias: jwt-secret
  secretObjects:
    - secretName: {{ include "hubspotService.fullname" . }}-kv
      type: Opaque
      data:
        - objectName: hubspot-api-tokens
          key: hubspot-api-tokens
        - objectName: otp-webhook-token
          key: otp-webhook-token
        - objectName: redis-password
          key: redis-password
        - objectName: jwt-secret
          key: jwt-secret
