// Generado de prod_tiv.detail_profiles + profiles (apoyo familiar). Contenido
// rico del reporte Tour Vocacional UCSP (plantilla Albeyron). NO editar a mano.
package query

type leSenneBlocks struct{ Potencialidades, Oportunidades, PerfilAcademico, Recomendaciones string }

var leSenneDetail = map[string]leSenneBlocks{
	"APASIONADO": {"Decidido Ambicioso, Don de mando, Le importa valores como familia, patria y religión, Serviciales, Honorables, Trabajador, Constante, Idealista, Capaz de organizarse, Sacrificarse.", "Tienden a la impaciencia y responder agresivamente. Pueden caer en el autoritarismo, ser impulsivos en sus decisiones. Puede volverse rencoroso, desconfiado, y ordenado en exceso.", "Se le da bien un trabajo: ordenado, con valores fuertes, relaciones interpersonales estables, responsabilidades claras. Además, rinde bien en trabajos sacrificados o con grandes responsabilidades que requieren de gran concentración y entrega. No tolera las injusticias", "Busque las razones que lo motivan a actuar. Encuentre un ideal o algo que lo apasione. Trabaje en el conocimiento de sí mismo, de sus fortalezas y debilidades. Si es creyente, fortalezca su fe con razones sólidas. Trabaje en equipo."},
	"COLERICO": {"Don de iniciativa y optimismo. Extrovertidos, alegres y de buen humor. Se mantiene en constante actividad, práctico. Generoso, servicial, independiente, improvisador. No sabe guardar rencor, perdona fácil.", "Tiende a ser cambiante en gustos, amigos, decisiones. Le cuesta la disciplina, las metas a largo plazo y conocerse a sí mismo, se distrae con facilidad. Puede tener arranques cortos de cólera que olvida fácilmente. Tiende a ocuparse de muchas cosas a la vez sin llegar a terminarlas.", "Se le da bien un trabajo: Que lo mantenga en constante actividad, en equipo y con metas a corto plazo. Trabajos creativos de soluciones prácticas y rápidas que no impliquen demasiada reflexión y que lo motiven constantemente. Con intereses positivos, sociales y políticos", "Encuentreun ideal o valores que puedan orientarlo. Otórguese un tiempo para reflexionar sobre sí mismo. No se permita dejar las cosas a medias, termínelas. Trabaje en su orden y disciplina con un horario.Manténgase ocupado y ponga en práctica todo lo aprendido."},
	"SENTIMENTAL": {"Introvertido e inclinado a la vida interior Sensible, templado, conservador, idealista. Le atrae lo estético Auténtico, equilibrado. Tiende al orden, método y perfeccionismo. De una rica vida interior.", "Tiende a ser vulnerable a las críticas y reproches. Tímido, indeciso y que suele desconfiar de sí mismo.", "Se le da bien un trabajo: Que mantenga un ambiente comprensivo, que se centre en los avances más que en los fracasos. Se le da bien los trabajos rutinarios y estables, con pocos cambios. Prefiere trabajos concretos y relacionados con lo afectivo como ayudar a los demás.", "Trabaje en su autoconfianza. Esfuércese por ver el lado positivo de todo lo que le acontece. Trabaje en equipo, y trate de manifestar aquello que no le agrada. Pruebe de vez en cuando algo nuevo, trate de salir de la rutina."},
	"NERVIOSO": {"Tiende a ser idealista, busca emociones nuevas por lo que pierde constancia. Sensible a la belleza Socialmente agradable, amable, generoso, de sonrisa fácil, amigable.", "Tiende a ser cambiante en sus emociones, impulsivo y poco constante. Puede buscar lo fácil y cómodo, y exagerar las cosas, o embellecerlas o por el contrario ser fatalista. Corre el peligro de la indisciplina, vanidad, engreimiento.", "Se le da bien un trabajo: Relacionado con lo artístico, la apreciación de la belleza. Le costará trabajos que exijan memorización, abstracción o razonamientos intensos. Prefiere trabajos relacionados a lo emotivo, que no exijan sobre esfuerzos, que le dé cierta libertad. Evitan las carreras frías o relacionadas con matemáticas.", "Trabaje en su organización con un horario y en terminar bien sus tareas. Trate de plantearse metas posibles a corto plazo. Promueva su autodominio, disciplina y valores como el orden, puntualidad y responsabilidad."},
	"SANGUINEO": {"Amante de la vida, auténtico, aprovecha las oportunidades. Poco expresivo, calmado, analítico. Tiende a una gran destreza manual, práctico. Independiente en sus juicios, diplomático, observador.", "Puede tender a sentimientos negativos como egoísmo, placeres momentáneos, curiosidad mal sana. Le hace falta encontrar convicciones profundas, puede caer en la superficialidad, insensibilidad e inconstancia.", "Se le da bien un trabajo: Que requiera de comprensión rápida y claridad en las ideas y juicio crítico. Aunque no lo disfrute es conveniente un ambiente disciplinado, con reglas claras y de altas motivaciones.", "Desarrolle sus dotes artísticas sea en música u otro tipo de artes. Trabaje en su planificación escolar, sírvase de trazarse metas y esfuércese por cumplirlas. Trabaje en equipo. Busque un ideal o motivación alta. Únase a voluntariados y diversos tipos de ayuda."},
	"FLEMATICO": {"Reservado, tranquilo, sencillo, de buen juicio, ordenado, puntual y limpio. Tiende a ser firme en sus decisiones, reflexivo, y adaptable. Sociables, valora a las personas. Previsor", "Tiende al perfeccionismo, obstinación y a ser rutinario. Poco espíritu de colaboración, difícil de improvisar.", "Se le da bien un trabajo de Intereses intelectuales profundos, que le permita crecer y recibir motivaciones. Se siente bien trabajando solo, de funciones metódicas y rutinarias y que requieren organización. Le resulta difícil los trabajos creativos o de innovación.", "Busque actividades que le agrade donde pueda relacionarse con otros. Permítase experimentar actividades creativas, de improvisación o de actividad física. Busque alguna actividad de ayuda a los demás con el que se sienta más identificado"},
	"AMORFO": {"Tiende a ser valiente, arriesgado, disfrutar de sus momentos de ocio, de pensamientos positivos, calmado, y muy sociables. Dócil, objetivo y observador y que gusta de los deportes.", "Le hace falta fuerza de voluntad para vencer sus inclinaciones placenteras, se emociona con facilidad, poca curiosidad, poco cuidado en su aspecto personal, tiende al desorden. Puede aplazar las tareas o querer aprovecharse del trabajo de sus compañeros.", "Se le da bien un trabajo con horarios flexibles que le permita desarrollar su sociabilidad, de proyectos a corto plazo y con recompensas inmediatas. Puede interesarle cuestiones de tipo natural", "Desarrolle hábitos de orden, responsabilidad y organización. Busque realizar trabajos tanto en equipo como individuales. Procure no aplazar sus actividades."},
	"APATICO": {"Tiende a ser muy objetivo, con valores fuertes, conservador, de hábitos buenos adquiridos.Disciplinado, fiel e imaginativo. Gustade la soledad que le permite ser reflexivo, profundo y dócil.", "Tiende a no encontrar una motivación para lo que hace, puede llegar a no apreciarse positivamente. Tiende a ser rencoroso.", "Se le da bien los trabajos relacionado a las ciencias abstractas y que tenga constantes motivaciones externas. Trabajos de carácter rutinario, de organización. Si le interesa le va bien con los números.", "Experimente actividades que requieran mucha energía. Deportes, excursiones, etc. Trabaje en su disciplina académica y busque un ideal que le permita estar motivado. Valore más sus aspectos positivos que los que tiene por trabajar."},
}

var familiaText = map[string]string{
	"FELICIDADES": "Estimado participante, las relaciones familiares son un pilar muy importante para tomar cualquier decisión, incluida nuestras elecciones profesionales. Tu familia y tú van haciendo un buen trabajo ¡sigue así!, mantén esa comunicación constante con tus familiares más cercanos, esto te permitirá clarificar aún más tu decisión profesional. Sigue fortaleciendo tu autonomía, sin olvidar escuchar los consejos de los adultos. ¡Adelante!",
	"ALERTA": "Estimado participante, las relaciones familiares son un pilar muy importante para tomar cualquier decisión, incluida nuestras elecciones profesionales. Recuerda que, debido a la edad en la que te encuentras es necesario que tus padres o apoderados conozcan tus intereses vocacionales, y el porqué de estos. Sabemos que aun te cuesta comunicarte y tomar decisiones con autonomía, por ello te recomendamos buscar toda la información que sea necesaria acerca de las profesiones que tienes en mente; y al mismo tiempo buscar técnicas de comunicación asertiva que puedas aplicar con tus familiares más cercanos. ¡Ánimo, tú puedes!",
	"PELIGRO": "Estimado participante, las relaciones familiares son un pilar muy importante para tomar cualquier decisión, incluida nuestras elecciones profesionales. Recuerda que, debido a la edad en la que te encuentras es necesario que tus padres o apoderados conozcan tus intereses vocacionales, y el porqué de estos. Sabemos que aun te cuesta mucho comunicarte y tomar decisiones con autonomía, por ello te recomendamos buscar el apoyo de algún especialista para que puedas desarrollar una comunicación más asertiva con tus familiares más cercanos. Por otro lado, es necesario que busques más información acerca de tus intereses vocacionales, de lo contrario corres el riesgo de tomar una decisión que no se adapte a ti. ¡Ánimo, a trabajar!",
}
