apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "keysService.fullname" . }}-spc
  labels:
    {{- include "keysService.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.keyVault.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.global.keyVault.name | quote }}
    tenantId: {{ .Values.global.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: keys-service-sql-password
          objectType: secret
          objectAlias: sql-password
        - |
          objectName: users-service-jwt-secret
          objectType: secret
          objectAlias: jwt-secret
  secretObjects:
    - secretName: {{ include "keysService.fullname" . }}-kv
      type: Opaque
      data:
        - objectName: sql-password
          key: sql-password
        - objectName: jwt-secret
          key: jwt-secret
