apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mssqlServer.fullname" . }}
  labels:
    {{- include "mssqlServer.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mssqlServer.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "mssqlServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mssqlServer.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: "true"
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10001  # mssql user
      containers:
        - name: mssql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mssql
              containerPort: 1433
              protocol: TCP
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "{{ .Values.edition }}"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mssqlServer.fullname" . }}-sa
                  key: SA_PASSWORD
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
            - name: kv-secrets
              mountPath: /mnt/kv
              readOnly: true
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
        - name: kv-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "mssqlServer.fullname" . }}-spc
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mssql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
{{- end }}
